// Generated from https://apis.datos.gob.ar/georef/api/localidades?provincia=santa+fe
// Paraná se agrega manual (es de Entre Ríos pero limítrofe).

export const PINNED_LOCALITIES: readonly string[] = [
  "Santa Fe",
  "Santo Tomé",
  "Recreo",
  "Esperanza",
  "Paraná",
  "Laguna Paiva",
];

export const OTHER_LOCALITIES: readonly string[] = [
  "Aarón Castellanos",
  "Acébal",
  "Aguará Grande",
  "Albarellos",
  "Alcorta",
  "Aldao",
  "Alejandra",
  "Alvear",
  "Ambrosetti",
  "Amenábar",
  "Angel Gallardo",
  "Angeloni",
  "Angélica",
  "Arbilla",
  "Arequito",
  "Arminda",
  "Armstrong",
  "Arocena",
  "Arroyo Aguiar",
  "Arroyo Ceibal",
  "Arroyo Leyes",
  "Arroyo Seco",
  "Arrufo",
  "Arteaga",
  "Ataliva",
  "Aurelia",
  "Avellaneda",
  "Balneario La Verde",
  "Balneario Monje",
  "Barrancas",
  "Barrio Arroyo del Medio",
  "Barrio Caima",
  "Barrio Cicarelli",
  "Barrio El Pacaá - Barrio Comipini",
  "Barrio Mitre",
  "Barrios Acapulco y Veracruz",
  "Bauer y Sigel",
  "Bella Italia",
  "Beravebú",
  "Berna",
  "Bernardo de Irigoyen",
  "Bigand",
  "Bombal",
  "Bouquet",
  "Bustinza",
  "Cabal",
  "Cacique Ariacaiquín",
  "Cafferata",
  "Calchaquí",
  "Campo Andino",
  "Candioti",
  "Capitán Bermúdez",
  "Capivara",
  "Carcarañá",
  "Carlos Pellegrini",
  "Carmen",
  "Carmen del Sauce",
  "Carreras",
  "Carrizales",
  "Casalegno",
  "Casas",
  "Casilda",
  "Castelar",
  "Castellanos",
  "Cavour",
  "Cayastacito",
  "Cayastá",
  "Cañada Ombú",
  "Cañada Rica",
  "Cañada Rosquín",
  "Cañada de Gómez",
  "Cañada del Ucle",
  "Centeno",
  "Cepeda",
  "Ceres",
  "Chabas",
  "Chapuy",
  "Chañar Ladeado",
  "Chovet",
  "Christophersen",
  "Classon",
  "Colmena",
  "Colonia Ana",
  "Colonia Belgrano",
  "Colonia Bicha",
  "Colonia Bossi",
  "Colonia Cello",
  "Colonia Dolores",
  "Colonia Durán",
  "Colonia Margarita",
  "Colonia Médici",
  "Colonia Raquel",
  "Colonia Rosa",
  "Constanza",
  "Coronda",
  "Coronel Arnold",
  "Coronel Bogado",
  "Coronel Fraga",
  "Coronel Rodolfo S. Domínguez",
  "Correa",
  "Crispi",
  "Cuatro Esquinas",
  "Cululú",
  "Curupaytí",
  "Desvío Arijón",
  "Diego de Alvear",
  "Díaz",
  "Egusquiza",
  "El Araza",
  "El Caramelo",
  "El Rabón",
  "El Trébol",
  "Elisa",
  "Elortondo",
  "Emilia",
  "Empalme San Carlos",
  "Empalme Villa Constitución",
  "Esmeralda",
  "Estación Clucellas",
  "Estación Presidente Roca",
  "Estación Saguier",
  "Esteban Rams",
  "Esther",
  "Eusebia y Carolina",
  "Eustolia",
  "Felicia",
  "Fighiera",
  "Firmat",
  "Florencia",
  "Fortín Olmos",
  "Franck",
  "Fray Luis Beltrán",
  "Frontera",
  "Fuentes",
  "Funes",
  "Gaboto",
  "Garabato",
  "Garibaldi",
  "Gato Colorado",
  "General Gelly",
  "General Lagos",
  "Gessler",
  "Gobernador Crespo",
  "Godoy",
  "Golondrina",
  "Granadero Baigorria",
  "Gregoria Pérez de Denis",
  "Grutly",
  "Guadalupe Norte",
  "Gálvez",
  "Gödeken",
  "Helvecia",
  "Hersilia",
  "Hipatía",
  "Huanqueros",
  "Hughes",
  "Humberto Primo",
  "Humboldt",
  "Ibarlucea",
  "Ingeniero Chanourdie",
  "Intiyaco",
  "Irigoyen",
  "Jacinto L. Aráuz",
  "Josefina",
  "Juan B. Molina",
  "Juncal",
  "Kilómetro 101",
  "Kilómetro 115",
  "La Brava",
  "La Cabral",
  "La Chispa",
  "La Criolla",
  "La Gallareta",
  "La Isleta",
  "La Lucila",
  "La Pelada",
  "La Penca y Caraguatá",
  "La Rubia",
  "La Sarita",
  "La Vanguardia",
  "Labordeboy",
  "Landeta",
  "Lanteri",
  "Larguía",
  "Larrechea",
  "Las Avispas",
  "Las Bandurrias",
  "Las Garzas",
  "Las Palmeras",
  "Las Parejas",
  "Las Petacas",
  "Las Rosas",
  "Las Toscas",
  "Las Tunas",
  "Lazzarino",
  "Lehmann",
  "Llambi Campbell",
  "Logroño",
  "Loma Alta",
  "Los Amores",
  "Los Cardos",
  "Los Laureles",
  "Los Molinos",
  "Los Muchachos - La Alborada",
  "Los Nogales",
  "Los Quirquinchos",
  "Los Zapallos",
  "Lucio V. López",
  "Luis Palacios",
  "López",
  "Maciel",
  "Maggiolo",
  "Malabrigo",
  "Marcelino Escalada",
  "Margarita",
  "María Juana",
  "María Luisa",
  "María Susana",
  "María Teresa",
  "Matilde",
  "Melincué",
  "Miguel Torres",
  "Moisés Ville",
  "Monigotes",
  "Monje",
  "Monte Flores",
  "Monte Vera",
  "Montefiore",
  "Montes de Oca",
  "Murphy",
  "Máximo Paz",
  "Naré",
  "Nelson",
  "Nueva Lehmann",
  "Nuevo Torino",
  "Oliveros",
  "Palacios",
  "Paraje 29",
  "Paraje Chaco Chico",
  "Paraje La Costa",
  "Paraje San Manuel",
  "Pavón",
  "Pavón Arriba",
  "Pedro Gómez Cello",
  "Peyrano",
  "Piamonte",
  "Pilar",
  "Piñero",
  "Plaza Clucellas",
  "Plaza Matilde",
  "Plaza Saguier",
  "Pozo Borrado",
  "Pozo de los Indios",
  "Presidente Roca",
  "Progreso",
  "Providencia",
  "Pueblo Andino",
  "Pueblo Esther",
  "Pueblo Marini",
  "Pueblo Muñóz",
  "Pueblo Santa Lucía",
  "Pueblo Uranga",
  "Puerto Aragón",
  "Puerto Arroyo Seco",
  "Puerto General San Martín",
  "Puerto Reconquista",
  "Pujato",
  "Pérez",
  "Rafaela",
  "Ramayón",
  "Ramona",
  "Reconquista",
  "Ricardone",
  "Rincón Norte",
  "Rincón Potrero",
  "Roldán",
  "Romang",
  "Rosario",
  "Rueda",
  "Rufino",
  "Sa Pereyra",
  "Saladero Mariano Cabal",
  "Salto Grande",
  "San Agustín",
  "San Antonio",
  "San Antonio de Obligado",
  "San Bernardo",
  "San Carlos Centro",
  "San Carlos Norte",
  "San Carlos Sud",
  "San Cristóbal",
  "San Eduardo",
  "San Eugenio",
  "San Fabián",
  "San Francisco de Santa Fe",
  "San Genaro",
  "San Genaro Norte",
  "San Gregorio",
  "San Guillermo",
  "San Javier",
  "San Jerónimo Norte",
  "San Jerónimo Sud",
  "San Jerónimo del Sauce",
  "San Jorge",
  "San José de la Esquina",
  "San José del Rincón",
  "San Justo",
  "San Lorenzo",
  "San Mariano",
  "San Martín Norte",
  "San Martín de las Escobas",
  "San Vicente",
  "Sancti Spiritu",
  "Sanford",
  "Santa Clara de Buena Vista",
  "Santa Clara de Saguier",
  "Santa Isabel",
  "Santa Margarita",
  "Santa Rosa de Calchines",
  "Santa Teresa",
  "Santo Domingo",
  "Santurce",
  "Sargento Cabral",
  "Sarmiento",
  "Sastre",
  "Sauce Viejo",
  "Serodino",
  "Silva",
  "Soldini",
  "Soledad",
  "Stephenson",
  "Suardi",
  "Sunchales",
  "Susana",
  "Tacuarendí",
  "Tacural",
  "Tartagal",
  "Teodelina",
  "Theobald",
  "Timbúes",
  "Toba",
  "Tortugas",
  "Tostado",
  "Totoras",
  "Traill",
  "Venado Tuerto",
  "Vera",
  "Vera y Pintado",
  "Videla",
  "Vila",
  "Villa Adelina",
  "Villa Amelia",
  "Villa Ana",
  "Villa Cañás",
  "Villa Constitución",
  "Villa Eloísa",
  "Villa Elvira",
  "Villa Gobernador Gálvez",
  "Villa Guillermina",
  "Villa Josefina",
  "Villa La Rivera (Oliveros)",
  "Villa La Rivera (Pueblo Andino)",
  "Villa Laura",
  "Villa Minetti",
  "Villa Mugueta",
  "Villa Ocampo",
  "Villa San José",
  "Villa Saralegui",
  "Villa Trinidad",
  "Villa del Plata",
  "Villada",
  "Virginia",
  "Wheelwright",
  "Wildermuth",
  "Zavalla",
  "Zenón Pereyra",
  "Álvarez",
  "Ñanducita",
];

export const ALL_LOCALITIES: readonly string[] = [
  ...PINNED_LOCALITIES,
  ...OTHER_LOCALITIES,
];
